services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"


    #- Develop 2 :- windows which we use the git bash
    #- Develop 1 :- windows which we use the git bash


